### ISSUE TITLE
Feature Proposal: Limit minimum python version by EOL date

### ISSUE THREAD

**Issue by carterbox** [snok/latest-python-versions#3]
I would like to make the `min-version` argument optional by using the end of life dates to determine which python versions are no longer supported. Does this feature make sense and would you be interested in accepting a PR? For example:

yaml
```
- uses: snok/latest-python-versions@v1
  id: get-python-versions
  with:
    min-version: EOL
    max-version: latest
    include-prereleases: false
```
Would return `[3.7, 3.8, 3.9, 3.10]` because pythons less than 3.7 are already EOL. The end of life dates could be pulled from `endoflife.date/api/python.json`
