### ISSUE TITLE
Handling different OSes

### ISSUE THREAD

**Issue by ForeverWintr** [snok/latest-python-versions#8]
It seems like github does not provide all python versions on all OSes. For example, currently the [version-manifest](https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json) only has `3.9.15` for linux. 

As a result, I'm having trouble mixing `latest-python-versions` with an OS matrix. Is there a known solution to this? Here is the relevant section of my workflow:

```yml
  get-python-versions:
    runs-on: ubuntu-latest
    outputs:
      python-matrix: ${{ steps.get-python-versions-action.outputs.latest-python-versions }}
    steps:
    - uses: snok/latest-python-versions@v1.1.2
      id: get-python-versions-action
      with:
        min-version: 3.9
        include-prereleases: true

  test:
    needs: [lint, get-python-versions]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJson(needs.get-python-versions.outputs.python-matrix) }}
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4.2.0
      with:
        python-version: ${{ matrix.python-version }}
```
